version: "3.9"

services:
  api:
    build: ./
    ports:
      - 8080:8080
    environment:
      MONGODB_URI: mongodb://db/node-login
      SECRET: ${SECRET}
      RTSECRET: ${RTSECRET}
    volumes:
      - ./:/app

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - node-login:/data/db

volumes:
  node-login:
